- name: Copy web folder
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./
          remote: /var/www/html
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.PRIVATE_KEY }}